/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_ioctl_tmoe_startup_NativeLoader */

#ifndef _Included_cc_ioctl_tmoe_startup_NativeLoader
#define _Included_cc_ioctl_tmoe_startup_NativeLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_ioctl_tmoe_startup_NativeLoader
 * Method:    getpagesize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cc_ioctl_tmoe_startup_NativeLoader_getpagesize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
